// ptbaFormConfig.ts
import type { FormConfig, SelectOption } from "../../Global/types/formConfig";

const chronogrammeOptions = [
  { label: "Jan", value: "Jan" },
  { label: "Fév", value: "Fév" },
  { label: "Mar", value: "Mar" },
  { label: "Avr", value: "Avr" },
  { label: "Mai", value: "Mai" },
  { label: "Jun", value: "Jun" },
  { label: "Jul", value: "Jul" },
  { label: "Aoû", value: "Aoû" },
  { label: "Sep", value: "Sep" },
  { label: "Oct", value: "Oct" },
  { label: "Nov", value: "Nov" },
  { label: "Déc", value: "Déc" },
];

export const getPtbaFormConfig = (
  cadreAnalytiqueOptions: SelectOption[] = [],
  typeActivitesOptions: SelectOption[] = [],
  localiteOptions: SelectOption[] = [],
  acteurOptions: SelectOption[] = [],
  personnelOptions: SelectOption[] = [],
  uglOptions: SelectOption[] = [],
  cadreStrategiqueOptions: SelectOption[] = []
): FormConfig => ({
  steps: [
    { step: 1, title: "Identité" },
    { step: 2, title: "Coordonnées" }
  ],
  fields: [
    {
      name: "code_activite_ptba",
      label: "Code activité PTBA",
      type: "text",
      placeholder: "Ex: ACT001, PTBA01...",
      required: true,
      gridCols: 2,
      formStep: 1,
    },
    {
      name: "type_activite",
      label: "Type activité",
      type: "select",
      placeholder: "Sélectionner un type d'activité",
      required: true,
      options: typeActivitesOptions || [],
      gridCols: 2,
      formStep: 1,
    },
    {
      name: "intitule_activite_ptba",
      label: "Intitulé activité PTBA",
      type: "textarea",
      placeholder: "Intitulé de l'activité (max 200 caractères)",
      required: true,
      maxLength: 200,
      gridCols: 1,
      formStep: 1,
    },
    {
      name: "cadre_analytique",
      label: "Cadre analytique",
      type: "select",
      placeholder: "Sélectionner un cadre analytique",
      required: true,
      options: cadreAnalytiqueOptions || [],
      gridCols: 1,
      formStep: 1,
    },
    {
      name: "chronogramme",
      label: "Chronogramme",
      type: "checkbox-group",
      multiple: true,
      required: true,
      options: chronogrammeOptions,
      gridCols: 1,
      formStep: 1,
    },
    {
      name: "localites_ptba",
      label: "Localités",
      type: "multiselect",
      placeholder: "Sélectionner une ou plusieurs localités",
      required: true,
      options: localiteOptions || [],
      gridCols: 2,
      formStep: 2,
    },
    {
      name: "code_crp",
      label: "Cadre strategique",
      type: "select",
      placeholder: "Sélectionner un cadre stratégique",
      required: false,
      options: cadreStrategiqueOptions || [],
      gridCols: 2,
      formStep: 2,
    },
    {
      name: "partenaire_conserne_ptba",
      label: "Partenaires concernés",
      type: "multiselect",
      placeholder: "Sélectionner un ou plusieurs partenaires",
      required: true,
      options: acteurOptions || [],
      gridCols: 1,
      formStep: 2,
    },
    {
      name: "responsable_ptba",
      label: "Responsable PTBA",
      type: "select",
      placeholder: "Sélectionner un responsable",
      required: false,
      options: personnelOptions || [],
      gridCols: 2,
      formStep: 2,
    },
    {
      name: "ugl_ptba",
      label: "Unité de gestion",
      type: "select",
      placeholder: "Sélectionner une unité de gestion",
      required: false,
      options: uglOptions || [],
      gridCols: 2,
      formStep: 2,
    },
  ]
});