/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedProgrammationParametrageMarchesRouteRouteImport } from './routes/_authenticated/programmation/parametrage-marches/route'
import { Route as AuthenticatedParametrageAutresRouteRouteImport } from './routes/_authenticated/parametrage/autres/route'
import { Route as AuthenticatedSuiviResultatsSuiviIndicateursIndexRouteImport } from './routes/_authenticated/suivi-resultats/suivi-indicateurs/index'
import { Route as AuthenticatedRapportPtbaIndexRouteImport } from './routes/_authenticated/rapport/ptba/index'
import { Route as AuthenticatedRapportIndicateursIndexRouteImport } from './routes/_authenticated/rapport/indicateurs/index'
import { Route as AuthenticatedRapportEtatDesActivitesIndexRouteImport } from './routes/_authenticated/rapport/etat-des-activites/index'
import { Route as AuthenticatedRapportDecaissementIndexRouteImport } from './routes/_authenticated/rapport/decaissement/index'
import { Route as AuthenticatedProjetProgrammeUnitesDeGestionIndexRouteImport } from './routes/_authenticated/projet-programme/unites-de-gestion/index'
import { Route as AuthenticatedProjetProgrammeProjetsIndexRouteImport } from './routes/_authenticated/projet-programme/projets/index'
import { Route as AuthenticatedProgrammePagesTestIndexRouteImport } from './routes/_authenticated/programme/pagesTest/index'
import { Route as AuthenticatedProgrammeListeIndexRouteImport } from './routes/_authenticated/programme/liste/index'
import { Route as AuthenticatedProgrammeIndicateursPerformanceIndexRouteImport } from './routes/_authenticated/programme/indicateurs-performance/index'
import { Route as AuthenticatedProgrammeIndicateursCmrIndexRouteImport } from './routes/_authenticated/programme/indicateurs-cmr/index'
import { Route as AuthenticatedProgrammeCadreStrategiqueIndexRouteImport } from './routes/_authenticated/programme/cadre-strategique/index'
import { Route as AuthenticatedProgrammeCadreAnalytiqueIndexRouteImport } from './routes/_authenticated/programme/cadre-analytique/index'
import { Route as AuthenticatedProgrammationSuiviPtbaIndexRouteImport } from './routes/_authenticated/programmation/suivi-ptba/index'
import { Route as AuthenticatedProgrammationPtbaIndexRouteImport } from './routes/_authenticated/programmation/ptba/index'
import { Route as AuthenticatedProgrammationProjetsIndexRouteImport } from './routes/_authenticated/programmation/projets/index'
import { Route as AuthenticatedProgrammationPpmsIndexRouteImport } from './routes/_authenticated/programmation/ppms/index'
import { Route as AuthenticatedProgrammationIndicateursPerformanceIndexRouteImport } from './routes/_authenticated/programmation/indicateurs-performance/index'
import { Route as AuthenticatedProgrammationIndicateursActivitesPtbaIndexRouteImport } from './routes/_authenticated/programmation/indicateurs-activites-ptba/index'
import { Route as AuthenticatedProgrammationContratPerformanceIndexRouteImport } from './routes/_authenticated/programmation/contrat-performance/index'
import { Route as AuthenticatedProgrammationActivitesProjetIndexRouteImport } from './routes/_authenticated/programmation/activites-projet/index'
import { Route as AuthenticatedProgrammationActivitesProgrammeIndexRouteImport } from './routes/_authenticated/programmation/activites-programme/index'
import { Route as AuthenticatedParametrageZoneDeCollecteIndexRouteImport } from './routes/_authenticated/parametrage/zone-de-collecte/index'
import { Route as AuthenticatedParametrageUtilisateursIndexRouteImport } from './routes/_authenticated/parametrage/utilisateurs/index'
import { Route as AuthenticatedParametragePlansDeSiteIndexRouteImport } from './routes/_authenticated/parametrage/plans-de-site/index'
import { Route as AuthenticatedParametragePartenaireFinancierIndexRouteImport } from './routes/_authenticated/parametrage/partenaire-financier/index'
import { Route as AuthenticatedParametrageLocalitesIndexRouteImport } from './routes/_authenticated/parametrage/localites/index'
import { Route as AuthenticatedParametrageDictionnaireIndicateursIndexRouteImport } from './routes/_authenticated/parametrage/dictionnaire-indicateurs/index'
import { Route as AuthenticatedParametrageActeursIndexRouteImport } from './routes/_authenticated/parametrage/acteurs/index'
import { Route as AuthenticatedSuiviResultatsSuiviIndicateursIdRouteImport } from './routes/_authenticated/suivi-resultats/suivi-indicateurs/$id'
import { Route as AuthenticatedProjetProgrammeProjetsIdRouteImport } from './routes/_authenticated/projet-programme/projets/$id'
import { Route as AuthenticatedProgrammationProjetsIdRouteImport } from './routes/_authenticated/programmation/projets/$id'
import { Route as AuthenticatedProgrammationContratPerformanceIdRouteImport } from './routes/_authenticated/programmation/contrat-performance/$id'
import { Route as authSetPasswordUidTokenRouteImport } from './routes/(auth)/set-password/$uid/$token'
import { Route as AuthenticatedProjetProgrammeProjetsIdIndexRouteImport } from './routes/_authenticated/projet-programme/projets/$id/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationParametrageMarchesRouteRoute =
  AuthenticatedProgrammationParametrageMarchesRouteRouteImport.update({
    id: '/programmation/parametrage-marches',
    path: '/programmation/parametrage-marches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametrageAutresRouteRoute =
  AuthenticatedParametrageAutresRouteRouteImport.update({
    id: '/parametrage/autres',
    path: '/parametrage/autres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuiviResultatsSuiviIndicateursIndexRoute =
  AuthenticatedSuiviResultatsSuiviIndicateursIndexRouteImport.update({
    id: '/suivi-resultats/suivi-indicateurs/',
    path: '/suivi-resultats/suivi-indicateurs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportPtbaIndexRoute =
  AuthenticatedRapportPtbaIndexRouteImport.update({
    id: '/rapport/ptba/',
    path: '/rapport/ptba/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportIndicateursIndexRoute =
  AuthenticatedRapportIndicateursIndexRouteImport.update({
    id: '/rapport/indicateurs/',
    path: '/rapport/indicateurs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportEtatDesActivitesIndexRoute =
  AuthenticatedRapportEtatDesActivitesIndexRouteImport.update({
    id: '/rapport/etat-des-activites/',
    path: '/rapport/etat-des-activites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRapportDecaissementIndexRoute =
  AuthenticatedRapportDecaissementIndexRouteImport.update({
    id: '/rapport/decaissement/',
    path: '/rapport/decaissement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetProgrammeUnitesDeGestionIndexRoute =
  AuthenticatedProjetProgrammeUnitesDeGestionIndexRouteImport.update({
    id: '/projet-programme/unites-de-gestion/',
    path: '/projet-programme/unites-de-gestion/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetProgrammeProjetsIndexRoute =
  AuthenticatedProjetProgrammeProjetsIndexRouteImport.update({
    id: '/projet-programme/projets/',
    path: '/projet-programme/projets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammePagesTestIndexRoute =
  AuthenticatedProgrammePagesTestIndexRouteImport.update({
    id: '/programme/pagesTest/',
    path: '/programme/pagesTest/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammeListeIndexRoute =
  AuthenticatedProgrammeListeIndexRouteImport.update({
    id: '/programme/liste/',
    path: '/programme/liste/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammeIndicateursPerformanceIndexRoute =
  AuthenticatedProgrammeIndicateursPerformanceIndexRouteImport.update({
    id: '/programme/indicateurs-performance/',
    path: '/programme/indicateurs-performance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammeIndicateursCmrIndexRoute =
  AuthenticatedProgrammeIndicateursCmrIndexRouteImport.update({
    id: '/programme/indicateurs-cmr/',
    path: '/programme/indicateurs-cmr/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammeCadreStrategiqueIndexRoute =
  AuthenticatedProgrammeCadreStrategiqueIndexRouteImport.update({
    id: '/programme/cadre-strategique/',
    path: '/programme/cadre-strategique/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammeCadreAnalytiqueIndexRoute =
  AuthenticatedProgrammeCadreAnalytiqueIndexRouteImport.update({
    id: '/programme/cadre-analytique/',
    path: '/programme/cadre-analytique/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationSuiviPtbaIndexRoute =
  AuthenticatedProgrammationSuiviPtbaIndexRouteImport.update({
    id: '/programmation/suivi-ptba/',
    path: '/programmation/suivi-ptba/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationPtbaIndexRoute =
  AuthenticatedProgrammationPtbaIndexRouteImport.update({
    id: '/programmation/ptba/',
    path: '/programmation/ptba/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationProjetsIndexRoute =
  AuthenticatedProgrammationProjetsIndexRouteImport.update({
    id: '/programmation/projets/',
    path: '/programmation/projets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationPpmsIndexRoute =
  AuthenticatedProgrammationPpmsIndexRouteImport.update({
    id: '/programmation/ppms/',
    path: '/programmation/ppms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationIndicateursPerformanceIndexRoute =
  AuthenticatedProgrammationIndicateursPerformanceIndexRouteImport.update({
    id: '/programmation/indicateurs-performance/',
    path: '/programmation/indicateurs-performance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationIndicateursActivitesPtbaIndexRoute =
  AuthenticatedProgrammationIndicateursActivitesPtbaIndexRouteImport.update({
    id: '/programmation/indicateurs-activites-ptba/',
    path: '/programmation/indicateurs-activites-ptba/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationContratPerformanceIndexRoute =
  AuthenticatedProgrammationContratPerformanceIndexRouteImport.update({
    id: '/programmation/contrat-performance/',
    path: '/programmation/contrat-performance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationActivitesProjetIndexRoute =
  AuthenticatedProgrammationActivitesProjetIndexRouteImport.update({
    id: '/programmation/activites-projet/',
    path: '/programmation/activites-projet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationActivitesProgrammeIndexRoute =
  AuthenticatedProgrammationActivitesProgrammeIndexRouteImport.update({
    id: '/programmation/activites-programme/',
    path: '/programmation/activites-programme/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametrageZoneDeCollecteIndexRoute =
  AuthenticatedParametrageZoneDeCollecteIndexRouteImport.update({
    id: '/parametrage/zone-de-collecte/',
    path: '/parametrage/zone-de-collecte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametrageUtilisateursIndexRoute =
  AuthenticatedParametrageUtilisateursIndexRouteImport.update({
    id: '/parametrage/utilisateurs/',
    path: '/parametrage/utilisateurs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametragePlansDeSiteIndexRoute =
  AuthenticatedParametragePlansDeSiteIndexRouteImport.update({
    id: '/parametrage/plans-de-site/',
    path: '/parametrage/plans-de-site/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametragePartenaireFinancierIndexRoute =
  AuthenticatedParametragePartenaireFinancierIndexRouteImport.update({
    id: '/parametrage/partenaire-financier/',
    path: '/parametrage/partenaire-financier/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametrageLocalitesIndexRoute =
  AuthenticatedParametrageLocalitesIndexRouteImport.update({
    id: '/parametrage/localites/',
    path: '/parametrage/localites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametrageDictionnaireIndicateursIndexRoute =
  AuthenticatedParametrageDictionnaireIndicateursIndexRouteImport.update({
    id: '/parametrage/dictionnaire-indicateurs/',
    path: '/parametrage/dictionnaire-indicateurs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametrageActeursIndexRoute =
  AuthenticatedParametrageActeursIndexRouteImport.update({
    id: '/parametrage/acteurs/',
    path: '/parametrage/acteurs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuiviResultatsSuiviIndicateursIdRoute =
  AuthenticatedSuiviResultatsSuiviIndicateursIdRouteImport.update({
    id: '/suivi-resultats/suivi-indicateurs/$id',
    path: '/suivi-resultats/suivi-indicateurs/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetProgrammeProjetsIdRoute =
  AuthenticatedProjetProgrammeProjetsIdRouteImport.update({
    id: '/projet-programme/projets/$id',
    path: '/projet-programme/projets/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationProjetsIdRoute =
  AuthenticatedProgrammationProjetsIdRouteImport.update({
    id: '/programmation/projets/$id',
    path: '/programmation/projets/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgrammationContratPerformanceIdRoute =
  AuthenticatedProgrammationContratPerformanceIdRouteImport.update({
    id: '/programmation/contrat-performance/$id',
    path: '/programmation/contrat-performance/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authSetPasswordUidTokenRoute = authSetPasswordUidTokenRouteImport.update({
  id: '/(auth)/set-password/$uid/$token',
  path: '/set-password/$uid/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetProgrammeProjetsIdIndexRoute =
  AuthenticatedProjetProgrammeProjetsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetProgrammeProjetsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/parametrage/autres': typeof AuthenticatedParametrageAutresRouteRoute
  '/programmation/parametrage-marches': typeof AuthenticatedProgrammationParametrageMarchesRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/set-password/$uid/$token': typeof authSetPasswordUidTokenRoute
  '/programmation/contrat-performance/$id': typeof AuthenticatedProgrammationContratPerformanceIdRoute
  '/programmation/projets/$id': typeof AuthenticatedProgrammationProjetsIdRoute
  '/projet-programme/projets/$id': typeof AuthenticatedProjetProgrammeProjetsIdRouteWithChildren
  '/suivi-resultats/suivi-indicateurs/$id': typeof AuthenticatedSuiviResultatsSuiviIndicateursIdRoute
  '/parametrage/acteurs/': typeof AuthenticatedParametrageActeursIndexRoute
  '/parametrage/dictionnaire-indicateurs/': typeof AuthenticatedParametrageDictionnaireIndicateursIndexRoute
  '/parametrage/localites/': typeof AuthenticatedParametrageLocalitesIndexRoute
  '/parametrage/partenaire-financier/': typeof AuthenticatedParametragePartenaireFinancierIndexRoute
  '/parametrage/plans-de-site/': typeof AuthenticatedParametragePlansDeSiteIndexRoute
  '/parametrage/utilisateurs/': typeof AuthenticatedParametrageUtilisateursIndexRoute
  '/parametrage/zone-de-collecte/': typeof AuthenticatedParametrageZoneDeCollecteIndexRoute
  '/programmation/activites-programme/': typeof AuthenticatedProgrammationActivitesProgrammeIndexRoute
  '/programmation/activites-projet/': typeof AuthenticatedProgrammationActivitesProjetIndexRoute
  '/programmation/contrat-performance/': typeof AuthenticatedProgrammationContratPerformanceIndexRoute
  '/programmation/indicateurs-activites-ptba/': typeof AuthenticatedProgrammationIndicateursActivitesPtbaIndexRoute
  '/programmation/indicateurs-performance/': typeof AuthenticatedProgrammationIndicateursPerformanceIndexRoute
  '/programmation/ppms/': typeof AuthenticatedProgrammationPpmsIndexRoute
  '/programmation/projets/': typeof AuthenticatedProgrammationProjetsIndexRoute
  '/programmation/ptba/': typeof AuthenticatedProgrammationPtbaIndexRoute
  '/programmation/suivi-ptba/': typeof AuthenticatedProgrammationSuiviPtbaIndexRoute
  '/programme/cadre-analytique/': typeof AuthenticatedProgrammeCadreAnalytiqueIndexRoute
  '/programme/cadre-strategique/': typeof AuthenticatedProgrammeCadreStrategiqueIndexRoute
  '/programme/indicateurs-cmr/': typeof AuthenticatedProgrammeIndicateursCmrIndexRoute
  '/programme/indicateurs-performance/': typeof AuthenticatedProgrammeIndicateursPerformanceIndexRoute
  '/programme/liste/': typeof AuthenticatedProgrammeListeIndexRoute
  '/programme/pagesTest/': typeof AuthenticatedProgrammePagesTestIndexRoute
  '/projet-programme/projets/': typeof AuthenticatedProjetProgrammeProjetsIndexRoute
  '/projet-programme/unites-de-gestion/': typeof AuthenticatedProjetProgrammeUnitesDeGestionIndexRoute
  '/rapport/decaissement/': typeof AuthenticatedRapportDecaissementIndexRoute
  '/rapport/etat-des-activites/': typeof AuthenticatedRapportEtatDesActivitesIndexRoute
  '/rapport/indicateurs/': typeof AuthenticatedRapportIndicateursIndexRoute
  '/rapport/ptba/': typeof AuthenticatedRapportPtbaIndexRoute
  '/suivi-resultats/suivi-indicateurs/': typeof AuthenticatedSuiviResultatsSuiviIndicateursIndexRoute
  '/projet-programme/projets/$id/': typeof AuthenticatedProjetProgrammeProjetsIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/parametrage/autres': typeof AuthenticatedParametrageAutresRouteRoute
  '/programmation/parametrage-marches': typeof AuthenticatedProgrammationParametrageMarchesRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/set-password/$uid/$token': typeof authSetPasswordUidTokenRoute
  '/programmation/contrat-performance/$id': typeof AuthenticatedProgrammationContratPerformanceIdRoute
  '/programmation/projets/$id': typeof AuthenticatedProgrammationProjetsIdRoute
  '/suivi-resultats/suivi-indicateurs/$id': typeof AuthenticatedSuiviResultatsSuiviIndicateursIdRoute
  '/parametrage/acteurs': typeof AuthenticatedParametrageActeursIndexRoute
  '/parametrage/dictionnaire-indicateurs': typeof AuthenticatedParametrageDictionnaireIndicateursIndexRoute
  '/parametrage/localites': typeof AuthenticatedParametrageLocalitesIndexRoute
  '/parametrage/partenaire-financier': typeof AuthenticatedParametragePartenaireFinancierIndexRoute
  '/parametrage/plans-de-site': typeof AuthenticatedParametragePlansDeSiteIndexRoute
  '/parametrage/utilisateurs': typeof AuthenticatedParametrageUtilisateursIndexRoute
  '/parametrage/zone-de-collecte': typeof AuthenticatedParametrageZoneDeCollecteIndexRoute
  '/programmation/activites-programme': typeof AuthenticatedProgrammationActivitesProgrammeIndexRoute
  '/programmation/activites-projet': typeof AuthenticatedProgrammationActivitesProjetIndexRoute
  '/programmation/contrat-performance': typeof AuthenticatedProgrammationContratPerformanceIndexRoute
  '/programmation/indicateurs-activites-ptba': typeof AuthenticatedProgrammationIndicateursActivitesPtbaIndexRoute
  '/programmation/indicateurs-performance': typeof AuthenticatedProgrammationIndicateursPerformanceIndexRoute
  '/programmation/ppms': typeof AuthenticatedProgrammationPpmsIndexRoute
  '/programmation/projets': typeof AuthenticatedProgrammationProjetsIndexRoute
  '/programmation/ptba': typeof AuthenticatedProgrammationPtbaIndexRoute
  '/programmation/suivi-ptba': typeof AuthenticatedProgrammationSuiviPtbaIndexRoute
  '/programme/cadre-analytique': typeof AuthenticatedProgrammeCadreAnalytiqueIndexRoute
  '/programme/cadre-strategique': typeof AuthenticatedProgrammeCadreStrategiqueIndexRoute
  '/programme/indicateurs-cmr': typeof AuthenticatedProgrammeIndicateursCmrIndexRoute
  '/programme/indicateurs-performance': typeof AuthenticatedProgrammeIndicateursPerformanceIndexRoute
  '/programme/liste': typeof AuthenticatedProgrammeListeIndexRoute
  '/programme/pagesTest': typeof AuthenticatedProgrammePagesTestIndexRoute
  '/projet-programme/projets': typeof AuthenticatedProjetProgrammeProjetsIndexRoute
  '/projet-programme/unites-de-gestion': typeof AuthenticatedProjetProgrammeUnitesDeGestionIndexRoute
  '/rapport/decaissement': typeof AuthenticatedRapportDecaissementIndexRoute
  '/rapport/etat-des-activites': typeof AuthenticatedRapportEtatDesActivitesIndexRoute
  '/rapport/indicateurs': typeof AuthenticatedRapportIndicateursIndexRoute
  '/rapport/ptba': typeof AuthenticatedRapportPtbaIndexRoute
  '/suivi-resultats/suivi-indicateurs': typeof AuthenticatedSuiviResultatsSuiviIndicateursIndexRoute
  '/projet-programme/projets/$id': typeof AuthenticatedProjetProgrammeProjetsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/parametrage/autres': typeof AuthenticatedParametrageAutresRouteRoute
  '/_authenticated/programmation/parametrage-marches': typeof AuthenticatedProgrammationParametrageMarchesRouteRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/(auth)/set-password/$uid/$token': typeof authSetPasswordUidTokenRoute
  '/_authenticated/programmation/contrat-performance/$id': typeof AuthenticatedProgrammationContratPerformanceIdRoute
  '/_authenticated/programmation/projets/$id': typeof AuthenticatedProgrammationProjetsIdRoute
  '/_authenticated/projet-programme/projets/$id': typeof AuthenticatedProjetProgrammeProjetsIdRouteWithChildren
  '/_authenticated/suivi-resultats/suivi-indicateurs/$id': typeof AuthenticatedSuiviResultatsSuiviIndicateursIdRoute
  '/_authenticated/parametrage/acteurs/': typeof AuthenticatedParametrageActeursIndexRoute
  '/_authenticated/parametrage/dictionnaire-indicateurs/': typeof AuthenticatedParametrageDictionnaireIndicateursIndexRoute
  '/_authenticated/parametrage/localites/': typeof AuthenticatedParametrageLocalitesIndexRoute
  '/_authenticated/parametrage/partenaire-financier/': typeof AuthenticatedParametragePartenaireFinancierIndexRoute
  '/_authenticated/parametrage/plans-de-site/': typeof AuthenticatedParametragePlansDeSiteIndexRoute
  '/_authenticated/parametrage/utilisateurs/': typeof AuthenticatedParametrageUtilisateursIndexRoute
  '/_authenticated/parametrage/zone-de-collecte/': typeof AuthenticatedParametrageZoneDeCollecteIndexRoute
  '/_authenticated/programmation/activites-programme/': typeof AuthenticatedProgrammationActivitesProgrammeIndexRoute
  '/_authenticated/programmation/activites-projet/': typeof AuthenticatedProgrammationActivitesProjetIndexRoute
  '/_authenticated/programmation/contrat-performance/': typeof AuthenticatedProgrammationContratPerformanceIndexRoute
  '/_authenticated/programmation/indicateurs-activites-ptba/': typeof AuthenticatedProgrammationIndicateursActivitesPtbaIndexRoute
  '/_authenticated/programmation/indicateurs-performance/': typeof AuthenticatedProgrammationIndicateursPerformanceIndexRoute
  '/_authenticated/programmation/ppms/': typeof AuthenticatedProgrammationPpmsIndexRoute
  '/_authenticated/programmation/projets/': typeof AuthenticatedProgrammationProjetsIndexRoute
  '/_authenticated/programmation/ptba/': typeof AuthenticatedProgrammationPtbaIndexRoute
  '/_authenticated/programmation/suivi-ptba/': typeof AuthenticatedProgrammationSuiviPtbaIndexRoute
  '/_authenticated/programme/cadre-analytique/': typeof AuthenticatedProgrammeCadreAnalytiqueIndexRoute
  '/_authenticated/programme/cadre-strategique/': typeof AuthenticatedProgrammeCadreStrategiqueIndexRoute
  '/_authenticated/programme/indicateurs-cmr/': typeof AuthenticatedProgrammeIndicateursCmrIndexRoute
  '/_authenticated/programme/indicateurs-performance/': typeof AuthenticatedProgrammeIndicateursPerformanceIndexRoute
  '/_authenticated/programme/liste/': typeof AuthenticatedProgrammeListeIndexRoute
  '/_authenticated/programme/pagesTest/': typeof AuthenticatedProgrammePagesTestIndexRoute
  '/_authenticated/projet-programme/projets/': typeof AuthenticatedProjetProgrammeProjetsIndexRoute
  '/_authenticated/projet-programme/unites-de-gestion/': typeof AuthenticatedProjetProgrammeUnitesDeGestionIndexRoute
  '/_authenticated/rapport/decaissement/': typeof AuthenticatedRapportDecaissementIndexRoute
  '/_authenticated/rapport/etat-des-activites/': typeof AuthenticatedRapportEtatDesActivitesIndexRoute
  '/_authenticated/rapport/indicateurs/': typeof AuthenticatedRapportIndicateursIndexRoute
  '/_authenticated/rapport/ptba/': typeof AuthenticatedRapportPtbaIndexRoute
  '/_authenticated/suivi-resultats/suivi-indicateurs/': typeof AuthenticatedSuiviResultatsSuiviIndicateursIndexRoute
  '/_authenticated/projet-programme/projets/$id/': typeof AuthenticatedProjetProgrammeProjetsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/parametrage/autres'
    | '/programmation/parametrage-marches'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps/'
    | '/help-center/'
    | '/settings/'
    | '/users/'
    | '/set-password/$uid/$token'
    | '/programmation/contrat-performance/$id'
    | '/programmation/projets/$id'
    | '/projet-programme/projets/$id'
    | '/suivi-resultats/suivi-indicateurs/$id'
    | '/parametrage/acteurs/'
    | '/parametrage/dictionnaire-indicateurs/'
    | '/parametrage/localites/'
    | '/parametrage/partenaire-financier/'
    | '/parametrage/plans-de-site/'
    | '/parametrage/utilisateurs/'
    | '/parametrage/zone-de-collecte/'
    | '/programmation/activites-programme/'
    | '/programmation/activites-projet/'
    | '/programmation/contrat-performance/'
    | '/programmation/indicateurs-activites-ptba/'
    | '/programmation/indicateurs-performance/'
    | '/programmation/ppms/'
    | '/programmation/projets/'
    | '/programmation/ptba/'
    | '/programmation/suivi-ptba/'
    | '/programme/cadre-analytique/'
    | '/programme/cadre-strategique/'
    | '/programme/indicateurs-cmr/'
    | '/programme/indicateurs-performance/'
    | '/programme/liste/'
    | '/programme/pagesTest/'
    | '/projet-programme/projets/'
    | '/projet-programme/unites-de-gestion/'
    | '/rapport/decaissement/'
    | '/rapport/etat-des-activites/'
    | '/rapport/indicateurs/'
    | '/rapport/ptba/'
    | '/suivi-resultats/suivi-indicateurs/'
    | '/projet-programme/projets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/parametrage/autres'
    | '/programmation/parametrage-marches'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/help-center'
    | '/settings'
    | '/users'
    | '/set-password/$uid/$token'
    | '/programmation/contrat-performance/$id'
    | '/programmation/projets/$id'
    | '/suivi-resultats/suivi-indicateurs/$id'
    | '/parametrage/acteurs'
    | '/parametrage/dictionnaire-indicateurs'
    | '/parametrage/localites'
    | '/parametrage/partenaire-financier'
    | '/parametrage/plans-de-site'
    | '/parametrage/utilisateurs'
    | '/parametrage/zone-de-collecte'
    | '/programmation/activites-programme'
    | '/programmation/activites-projet'
    | '/programmation/contrat-performance'
    | '/programmation/indicateurs-activites-ptba'
    | '/programmation/indicateurs-performance'
    | '/programmation/ppms'
    | '/programmation/projets'
    | '/programmation/ptba'
    | '/programmation/suivi-ptba'
    | '/programme/cadre-analytique'
    | '/programme/cadre-strategique'
    | '/programme/indicateurs-cmr'
    | '/programme/indicateurs-performance'
    | '/programme/liste'
    | '/programme/pagesTest'
    | '/projet-programme/projets'
    | '/projet-programme/unites-de-gestion'
    | '/rapport/decaissement'
    | '/rapport/etat-des-activites'
    | '/rapport/indicateurs'
    | '/rapport/ptba'
    | '/suivi-resultats/suivi-indicateurs'
    | '/projet-programme/projets/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/parametrage/autres'
    | '/_authenticated/programmation/parametrage-marches'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/(auth)/set-password/$uid/$token'
    | '/_authenticated/programmation/contrat-performance/$id'
    | '/_authenticated/programmation/projets/$id'
    | '/_authenticated/projet-programme/projets/$id'
    | '/_authenticated/suivi-resultats/suivi-indicateurs/$id'
    | '/_authenticated/parametrage/acteurs/'
    | '/_authenticated/parametrage/dictionnaire-indicateurs/'
    | '/_authenticated/parametrage/localites/'
    | '/_authenticated/parametrage/partenaire-financier/'
    | '/_authenticated/parametrage/plans-de-site/'
    | '/_authenticated/parametrage/utilisateurs/'
    | '/_authenticated/parametrage/zone-de-collecte/'
    | '/_authenticated/programmation/activites-programme/'
    | '/_authenticated/programmation/activites-projet/'
    | '/_authenticated/programmation/contrat-performance/'
    | '/_authenticated/programmation/indicateurs-activites-ptba/'
    | '/_authenticated/programmation/indicateurs-performance/'
    | '/_authenticated/programmation/ppms/'
    | '/_authenticated/programmation/projets/'
    | '/_authenticated/programmation/ptba/'
    | '/_authenticated/programmation/suivi-ptba/'
    | '/_authenticated/programme/cadre-analytique/'
    | '/_authenticated/programme/cadre-strategique/'
    | '/_authenticated/programme/indicateurs-cmr/'
    | '/_authenticated/programme/indicateurs-performance/'
    | '/_authenticated/programme/liste/'
    | '/_authenticated/programme/pagesTest/'
    | '/_authenticated/projet-programme/projets/'
    | '/_authenticated/projet-programme/unites-de-gestion/'
    | '/_authenticated/rapport/decaissement/'
    | '/_authenticated/rapport/etat-des-activites/'
    | '/_authenticated/rapport/indicateurs/'
    | '/_authenticated/rapport/ptba/'
    | '/_authenticated/suivi-resultats/suivi-indicateurs/'
    | '/_authenticated/projet-programme/projets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  authSetPasswordUidTokenRoute: typeof authSetPasswordUidTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/parametrage-marches': {
      id: '/_authenticated/programmation/parametrage-marches'
      path: '/programmation/parametrage-marches'
      fullPath: '/programmation/parametrage-marches'
      preLoaderRoute: typeof AuthenticatedProgrammationParametrageMarchesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametrage/autres': {
      id: '/_authenticated/parametrage/autres'
      path: '/parametrage/autres'
      fullPath: '/parametrage/autres'
      preLoaderRoute: typeof AuthenticatedParametrageAutresRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suivi-resultats/suivi-indicateurs/': {
      id: '/_authenticated/suivi-resultats/suivi-indicateurs/'
      path: '/suivi-resultats/suivi-indicateurs'
      fullPath: '/suivi-resultats/suivi-indicateurs/'
      preLoaderRoute: typeof AuthenticatedSuiviResultatsSuiviIndicateursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapport/ptba/': {
      id: '/_authenticated/rapport/ptba/'
      path: '/rapport/ptba'
      fullPath: '/rapport/ptba/'
      preLoaderRoute: typeof AuthenticatedRapportPtbaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapport/indicateurs/': {
      id: '/_authenticated/rapport/indicateurs/'
      path: '/rapport/indicateurs'
      fullPath: '/rapport/indicateurs/'
      preLoaderRoute: typeof AuthenticatedRapportIndicateursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapport/etat-des-activites/': {
      id: '/_authenticated/rapport/etat-des-activites/'
      path: '/rapport/etat-des-activites'
      fullPath: '/rapport/etat-des-activites/'
      preLoaderRoute: typeof AuthenticatedRapportEtatDesActivitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapport/decaissement/': {
      id: '/_authenticated/rapport/decaissement/'
      path: '/rapport/decaissement'
      fullPath: '/rapport/decaissement/'
      preLoaderRoute: typeof AuthenticatedRapportDecaissementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projet-programme/unites-de-gestion/': {
      id: '/_authenticated/projet-programme/unites-de-gestion/'
      path: '/projet-programme/unites-de-gestion'
      fullPath: '/projet-programme/unites-de-gestion/'
      preLoaderRoute: typeof AuthenticatedProjetProgrammeUnitesDeGestionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projet-programme/projets/': {
      id: '/_authenticated/projet-programme/projets/'
      path: '/projet-programme/projets'
      fullPath: '/projet-programme/projets/'
      preLoaderRoute: typeof AuthenticatedProjetProgrammeProjetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programme/pagesTest/': {
      id: '/_authenticated/programme/pagesTest/'
      path: '/programme/pagesTest'
      fullPath: '/programme/pagesTest/'
      preLoaderRoute: typeof AuthenticatedProgrammePagesTestIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programme/liste/': {
      id: '/_authenticated/programme/liste/'
      path: '/programme/liste'
      fullPath: '/programme/liste/'
      preLoaderRoute: typeof AuthenticatedProgrammeListeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programme/indicateurs-performance/': {
      id: '/_authenticated/programme/indicateurs-performance/'
      path: '/programme/indicateurs-performance'
      fullPath: '/programme/indicateurs-performance/'
      preLoaderRoute: typeof AuthenticatedProgrammeIndicateursPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programme/indicateurs-cmr/': {
      id: '/_authenticated/programme/indicateurs-cmr/'
      path: '/programme/indicateurs-cmr'
      fullPath: '/programme/indicateurs-cmr/'
      preLoaderRoute: typeof AuthenticatedProgrammeIndicateursCmrIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programme/cadre-strategique/': {
      id: '/_authenticated/programme/cadre-strategique/'
      path: '/programme/cadre-strategique'
      fullPath: '/programme/cadre-strategique/'
      preLoaderRoute: typeof AuthenticatedProgrammeCadreStrategiqueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programme/cadre-analytique/': {
      id: '/_authenticated/programme/cadre-analytique/'
      path: '/programme/cadre-analytique'
      fullPath: '/programme/cadre-analytique/'
      preLoaderRoute: typeof AuthenticatedProgrammeCadreAnalytiqueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/suivi-ptba/': {
      id: '/_authenticated/programmation/suivi-ptba/'
      path: '/programmation/suivi-ptba'
      fullPath: '/programmation/suivi-ptba/'
      preLoaderRoute: typeof AuthenticatedProgrammationSuiviPtbaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/ptba/': {
      id: '/_authenticated/programmation/ptba/'
      path: '/programmation/ptba'
      fullPath: '/programmation/ptba/'
      preLoaderRoute: typeof AuthenticatedProgrammationPtbaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/projets/': {
      id: '/_authenticated/programmation/projets/'
      path: '/programmation/projets'
      fullPath: '/programmation/projets/'
      preLoaderRoute: typeof AuthenticatedProgrammationProjetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/ppms/': {
      id: '/_authenticated/programmation/ppms/'
      path: '/programmation/ppms'
      fullPath: '/programmation/ppms/'
      preLoaderRoute: typeof AuthenticatedProgrammationPpmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/indicateurs-performance/': {
      id: '/_authenticated/programmation/indicateurs-performance/'
      path: '/programmation/indicateurs-performance'
      fullPath: '/programmation/indicateurs-performance/'
      preLoaderRoute: typeof AuthenticatedProgrammationIndicateursPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/indicateurs-activites-ptba/': {
      id: '/_authenticated/programmation/indicateurs-activites-ptba/'
      path: '/programmation/indicateurs-activites-ptba'
      fullPath: '/programmation/indicateurs-activites-ptba/'
      preLoaderRoute: typeof AuthenticatedProgrammationIndicateursActivitesPtbaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/contrat-performance/': {
      id: '/_authenticated/programmation/contrat-performance/'
      path: '/programmation/contrat-performance'
      fullPath: '/programmation/contrat-performance/'
      preLoaderRoute: typeof AuthenticatedProgrammationContratPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/activites-projet/': {
      id: '/_authenticated/programmation/activites-projet/'
      path: '/programmation/activites-projet'
      fullPath: '/programmation/activites-projet/'
      preLoaderRoute: typeof AuthenticatedProgrammationActivitesProjetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/activites-programme/': {
      id: '/_authenticated/programmation/activites-programme/'
      path: '/programmation/activites-programme'
      fullPath: '/programmation/activites-programme/'
      preLoaderRoute: typeof AuthenticatedProgrammationActivitesProgrammeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametrage/zone-de-collecte/': {
      id: '/_authenticated/parametrage/zone-de-collecte/'
      path: '/parametrage/zone-de-collecte'
      fullPath: '/parametrage/zone-de-collecte/'
      preLoaderRoute: typeof AuthenticatedParametrageZoneDeCollecteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametrage/utilisateurs/': {
      id: '/_authenticated/parametrage/utilisateurs/'
      path: '/parametrage/utilisateurs'
      fullPath: '/parametrage/utilisateurs/'
      preLoaderRoute: typeof AuthenticatedParametrageUtilisateursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametrage/plans-de-site/': {
      id: '/_authenticated/parametrage/plans-de-site/'
      path: '/parametrage/plans-de-site'
      fullPath: '/parametrage/plans-de-site/'
      preLoaderRoute: typeof AuthenticatedParametragePlansDeSiteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametrage/partenaire-financier/': {
      id: '/_authenticated/parametrage/partenaire-financier/'
      path: '/parametrage/partenaire-financier'
      fullPath: '/parametrage/partenaire-financier/'
      preLoaderRoute: typeof AuthenticatedParametragePartenaireFinancierIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametrage/localites/': {
      id: '/_authenticated/parametrage/localites/'
      path: '/parametrage/localites'
      fullPath: '/parametrage/localites/'
      preLoaderRoute: typeof AuthenticatedParametrageLocalitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametrage/dictionnaire-indicateurs/': {
      id: '/_authenticated/parametrage/dictionnaire-indicateurs/'
      path: '/parametrage/dictionnaire-indicateurs'
      fullPath: '/parametrage/dictionnaire-indicateurs/'
      preLoaderRoute: typeof AuthenticatedParametrageDictionnaireIndicateursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametrage/acteurs/': {
      id: '/_authenticated/parametrage/acteurs/'
      path: '/parametrage/acteurs'
      fullPath: '/parametrage/acteurs/'
      preLoaderRoute: typeof AuthenticatedParametrageActeursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suivi-resultats/suivi-indicateurs/$id': {
      id: '/_authenticated/suivi-resultats/suivi-indicateurs/$id'
      path: '/suivi-resultats/suivi-indicateurs/$id'
      fullPath: '/suivi-resultats/suivi-indicateurs/$id'
      preLoaderRoute: typeof AuthenticatedSuiviResultatsSuiviIndicateursIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projet-programme/projets/$id': {
      id: '/_authenticated/projet-programme/projets/$id'
      path: '/projet-programme/projets/$id'
      fullPath: '/projet-programme/projets/$id'
      preLoaderRoute: typeof AuthenticatedProjetProgrammeProjetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/projets/$id': {
      id: '/_authenticated/programmation/projets/$id'
      path: '/programmation/projets/$id'
      fullPath: '/programmation/projets/$id'
      preLoaderRoute: typeof AuthenticatedProgrammationProjetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmation/contrat-performance/$id': {
      id: '/_authenticated/programmation/contrat-performance/$id'
      path: '/programmation/contrat-performance/$id'
      fullPath: '/programmation/contrat-performance/$id'
      preLoaderRoute: typeof AuthenticatedProgrammationContratPerformanceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/set-password/$uid/$token': {
      id: '/(auth)/set-password/$uid/$token'
      path: '/set-password/$uid/$token'
      fullPath: '/set-password/$uid/$token'
      preLoaderRoute: typeof authSetPasswordUidTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projet-programme/projets/$id/': {
      id: '/_authenticated/projet-programme/projets/$id/'
      path: '/'
      fullPath: '/projet-programme/projets/$id/'
      preLoaderRoute: typeof AuthenticatedProjetProgrammeProjetsIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjetProgrammeProjetsIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedProjetProgrammeProjetsIdRouteChildren {
  AuthenticatedProjetProgrammeProjetsIdIndexRoute: typeof AuthenticatedProjetProgrammeProjetsIdIndexRoute
}

const AuthenticatedProjetProgrammeProjetsIdRouteChildren: AuthenticatedProjetProgrammeProjetsIdRouteChildren =
  {
    AuthenticatedProjetProgrammeProjetsIdIndexRoute:
      AuthenticatedProjetProgrammeProjetsIdIndexRoute,
  }

const AuthenticatedProjetProgrammeProjetsIdRouteWithChildren =
  AuthenticatedProjetProgrammeProjetsIdRoute._addFileChildren(
    AuthenticatedProjetProgrammeProjetsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedParametrageAutresRouteRoute: typeof AuthenticatedParametrageAutresRouteRoute
  AuthenticatedProgrammationParametrageMarchesRouteRoute: typeof AuthenticatedProgrammationParametrageMarchesRouteRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedProgrammationContratPerformanceIdRoute: typeof AuthenticatedProgrammationContratPerformanceIdRoute
  AuthenticatedProgrammationProjetsIdRoute: typeof AuthenticatedProgrammationProjetsIdRoute
  AuthenticatedProjetProgrammeProjetsIdRoute: typeof AuthenticatedProjetProgrammeProjetsIdRouteWithChildren
  AuthenticatedSuiviResultatsSuiviIndicateursIdRoute: typeof AuthenticatedSuiviResultatsSuiviIndicateursIdRoute
  AuthenticatedParametrageActeursIndexRoute: typeof AuthenticatedParametrageActeursIndexRoute
  AuthenticatedParametrageDictionnaireIndicateursIndexRoute: typeof AuthenticatedParametrageDictionnaireIndicateursIndexRoute
  AuthenticatedParametrageLocalitesIndexRoute: typeof AuthenticatedParametrageLocalitesIndexRoute
  AuthenticatedParametragePartenaireFinancierIndexRoute: typeof AuthenticatedParametragePartenaireFinancierIndexRoute
  AuthenticatedParametragePlansDeSiteIndexRoute: typeof AuthenticatedParametragePlansDeSiteIndexRoute
  AuthenticatedParametrageUtilisateursIndexRoute: typeof AuthenticatedParametrageUtilisateursIndexRoute
  AuthenticatedParametrageZoneDeCollecteIndexRoute: typeof AuthenticatedParametrageZoneDeCollecteIndexRoute
  AuthenticatedProgrammationActivitesProgrammeIndexRoute: typeof AuthenticatedProgrammationActivitesProgrammeIndexRoute
  AuthenticatedProgrammationActivitesProjetIndexRoute: typeof AuthenticatedProgrammationActivitesProjetIndexRoute
  AuthenticatedProgrammationContratPerformanceIndexRoute: typeof AuthenticatedProgrammationContratPerformanceIndexRoute
  AuthenticatedProgrammationIndicateursActivitesPtbaIndexRoute: typeof AuthenticatedProgrammationIndicateursActivitesPtbaIndexRoute
  AuthenticatedProgrammationIndicateursPerformanceIndexRoute: typeof AuthenticatedProgrammationIndicateursPerformanceIndexRoute
  AuthenticatedProgrammationPpmsIndexRoute: typeof AuthenticatedProgrammationPpmsIndexRoute
  AuthenticatedProgrammationProjetsIndexRoute: typeof AuthenticatedProgrammationProjetsIndexRoute
  AuthenticatedProgrammationPtbaIndexRoute: typeof AuthenticatedProgrammationPtbaIndexRoute
  AuthenticatedProgrammationSuiviPtbaIndexRoute: typeof AuthenticatedProgrammationSuiviPtbaIndexRoute
  AuthenticatedProgrammeCadreAnalytiqueIndexRoute: typeof AuthenticatedProgrammeCadreAnalytiqueIndexRoute
  AuthenticatedProgrammeCadreStrategiqueIndexRoute: typeof AuthenticatedProgrammeCadreStrategiqueIndexRoute
  AuthenticatedProgrammeIndicateursCmrIndexRoute: typeof AuthenticatedProgrammeIndicateursCmrIndexRoute
  AuthenticatedProgrammeIndicateursPerformanceIndexRoute: typeof AuthenticatedProgrammeIndicateursPerformanceIndexRoute
  AuthenticatedProgrammeListeIndexRoute: typeof AuthenticatedProgrammeListeIndexRoute
  AuthenticatedProgrammePagesTestIndexRoute: typeof AuthenticatedProgrammePagesTestIndexRoute
  AuthenticatedProjetProgrammeProjetsIndexRoute: typeof AuthenticatedProjetProgrammeProjetsIndexRoute
  AuthenticatedProjetProgrammeUnitesDeGestionIndexRoute: typeof AuthenticatedProjetProgrammeUnitesDeGestionIndexRoute
  AuthenticatedRapportDecaissementIndexRoute: typeof AuthenticatedRapportDecaissementIndexRoute
  AuthenticatedRapportEtatDesActivitesIndexRoute: typeof AuthenticatedRapportEtatDesActivitesIndexRoute
  AuthenticatedRapportIndicateursIndexRoute: typeof AuthenticatedRapportIndicateursIndexRoute
  AuthenticatedRapportPtbaIndexRoute: typeof AuthenticatedRapportPtbaIndexRoute
  AuthenticatedSuiviResultatsSuiviIndicateursIndexRoute: typeof AuthenticatedSuiviResultatsSuiviIndicateursIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedParametrageAutresRouteRoute:
    AuthenticatedParametrageAutresRouteRoute,
  AuthenticatedProgrammationParametrageMarchesRouteRoute:
    AuthenticatedProgrammationParametrageMarchesRouteRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedProgrammationContratPerformanceIdRoute:
    AuthenticatedProgrammationContratPerformanceIdRoute,
  AuthenticatedProgrammationProjetsIdRoute:
    AuthenticatedProgrammationProjetsIdRoute,
  AuthenticatedProjetProgrammeProjetsIdRoute:
    AuthenticatedProjetProgrammeProjetsIdRouteWithChildren,
  AuthenticatedSuiviResultatsSuiviIndicateursIdRoute:
    AuthenticatedSuiviResultatsSuiviIndicateursIdRoute,
  AuthenticatedParametrageActeursIndexRoute:
    AuthenticatedParametrageActeursIndexRoute,
  AuthenticatedParametrageDictionnaireIndicateursIndexRoute:
    AuthenticatedParametrageDictionnaireIndicateursIndexRoute,
  AuthenticatedParametrageLocalitesIndexRoute:
    AuthenticatedParametrageLocalitesIndexRoute,
  AuthenticatedParametragePartenaireFinancierIndexRoute:
    AuthenticatedParametragePartenaireFinancierIndexRoute,
  AuthenticatedParametragePlansDeSiteIndexRoute:
    AuthenticatedParametragePlansDeSiteIndexRoute,
  AuthenticatedParametrageUtilisateursIndexRoute:
    AuthenticatedParametrageUtilisateursIndexRoute,
  AuthenticatedParametrageZoneDeCollecteIndexRoute:
    AuthenticatedParametrageZoneDeCollecteIndexRoute,
  AuthenticatedProgrammationActivitesProgrammeIndexRoute:
    AuthenticatedProgrammationActivitesProgrammeIndexRoute,
  AuthenticatedProgrammationActivitesProjetIndexRoute:
    AuthenticatedProgrammationActivitesProjetIndexRoute,
  AuthenticatedProgrammationContratPerformanceIndexRoute:
    AuthenticatedProgrammationContratPerformanceIndexRoute,
  AuthenticatedProgrammationIndicateursActivitesPtbaIndexRoute:
    AuthenticatedProgrammationIndicateursActivitesPtbaIndexRoute,
  AuthenticatedProgrammationIndicateursPerformanceIndexRoute:
    AuthenticatedProgrammationIndicateursPerformanceIndexRoute,
  AuthenticatedProgrammationPpmsIndexRoute:
    AuthenticatedProgrammationPpmsIndexRoute,
  AuthenticatedProgrammationProjetsIndexRoute:
    AuthenticatedProgrammationProjetsIndexRoute,
  AuthenticatedProgrammationPtbaIndexRoute:
    AuthenticatedProgrammationPtbaIndexRoute,
  AuthenticatedProgrammationSuiviPtbaIndexRoute:
    AuthenticatedProgrammationSuiviPtbaIndexRoute,
  AuthenticatedProgrammeCadreAnalytiqueIndexRoute:
    AuthenticatedProgrammeCadreAnalytiqueIndexRoute,
  AuthenticatedProgrammeCadreStrategiqueIndexRoute:
    AuthenticatedProgrammeCadreStrategiqueIndexRoute,
  AuthenticatedProgrammeIndicateursCmrIndexRoute:
    AuthenticatedProgrammeIndicateursCmrIndexRoute,
  AuthenticatedProgrammeIndicateursPerformanceIndexRoute:
    AuthenticatedProgrammeIndicateursPerformanceIndexRoute,
  AuthenticatedProgrammeListeIndexRoute: AuthenticatedProgrammeListeIndexRoute,
  AuthenticatedProgrammePagesTestIndexRoute:
    AuthenticatedProgrammePagesTestIndexRoute,
  AuthenticatedProjetProgrammeProjetsIndexRoute:
    AuthenticatedProjetProgrammeProjetsIndexRoute,
  AuthenticatedProjetProgrammeUnitesDeGestionIndexRoute:
    AuthenticatedProjetProgrammeUnitesDeGestionIndexRoute,
  AuthenticatedRapportDecaissementIndexRoute:
    AuthenticatedRapportDecaissementIndexRoute,
  AuthenticatedRapportEtatDesActivitesIndexRoute:
    AuthenticatedRapportEtatDesActivitesIndexRoute,
  AuthenticatedRapportIndicateursIndexRoute:
    AuthenticatedRapportIndicateursIndexRoute,
  AuthenticatedRapportPtbaIndexRoute: AuthenticatedRapportPtbaIndexRoute,
  AuthenticatedSuiviResultatsSuiviIndicateursIndexRoute:
    AuthenticatedSuiviResultatsSuiviIndicateursIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  authSetPasswordUidTokenRoute: authSetPasswordUidTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
